import 'package:VIEW_MODEL_PROJECT_IDENTIFIER_QW32/gen/colors.gen.dart';
import 'package:VIEW_MODEL_PROJECT_IDENTIFIER_QW32/presentation_layer/constants/text_style_const.dart';
import 'package:VIEW_MODEL_PROJECT_IDENTIFIER_QW32/presentation_layer/general/base/theme/app_colors_theme.dart';
import 'package:VIEW_MODEL_PROJECT_IDENTIFIER_QW32/presentation_layer/general/base/theme/app_text_theme.dart';

final class AppThemeConstants {
  static final appColors = AppColorsThemeExtension(
    background: ColorName.background,
    blue: ColorName.blue,
    e500: ColorName.e500,
    green: ColorName.green,
    i500: ColorName.i500,
    n0: ColorName.n0,
    n100: ColorName.n100,
    n1000: ColorName.n1000,
    n200: ColorName.n200,
    n25: ColorName.n25,
    n300: ColorName.n300,
    n400: ColorName.n400,
    n50: ColorName.n50,
    n500: ColorName.n500,
    n700: ColorName.n700,
    p100: ColorName.p100,
    p200: ColorName.p200,
    p300: ColorName.p300,
    p400: ColorName.p400,
    p500: ColorName.p500,
    p700: ColorName.p700,
    pink: ColorName.pink,
    purple: ColorName.purple,
    s100: ColorName.s100,
    s200: ColorName.s200,
    s300: ColorName.s300,
    s400: ColorName.s400,
    s500: ColorName.s500,
    s600: ColorName.s600,
    sc500: ColorName.sc500,
    w500: ColorName.w500,
    transparent: ColorName.transparent,
  );

  static const textTheme = AppTextThemeExtension(
    heading1Bold: TextStyleConst.heading1Bold,
    heading1SemiBold: TextStyleConst.heading1SemiBold,
    heading1Medium: TextStyleConst.heading1Medium,
    heading1Regular: TextStyleConst.heading1Regular,
    heading2Bold: TextStyleConst.heading2Bold,
    heading2SemiBold: TextStyleConst.heading2SemiBold,
    heading2Medium: TextStyleConst.heading2Medium,
    heading2Regular: TextStyleConst.heading2Regular,
    heading3Bold: TextStyleConst.heading3Bold,
    heading3SemiBold: TextStyleConst.heading3SemiBold,
    heading3Medium: TextStyleConst.heading3Medium,
    heading3Regular: TextStyleConst.heading3Regular,
    heading4Bold: TextStyleConst.heading4Bold,
    heading4SemiBold: TextStyleConst.heading4SemiBold,
    heading4Medium: TextStyleConst.heading4Medium,
    heading4Regular: TextStyleConst.heading4Regular,
    subHeading1Bold: TextStyleConst.subHeading1Bold,
    subHeading1SemiBold: TextStyleConst.subHeading1SemiBold,
    subHeading1Medium: TextStyleConst.subHeading1Medium,
    subHeading1Regular: TextStyleConst.subHeading1Regular,
    subHeading2Bold: TextStyleConst.subHeading2Bold,
    subHeading2SemiBold: TextStyleConst.subHeading2SemiBold,
    subHeading2Medium: TextStyleConst.subHeading2Medium,
    subHeading2Regular: TextStyleConst.subHeading2Regular,
    body1Bold: TextStyleConst.body1Bold,
    body1SemiBold: TextStyleConst.body1SemiBold,
    body1Medium: TextStyleConst.body1Medium,
    body1Regular: TextStyleConst.body1Regular,
    body2Bold: TextStyleConst.body2Bold,
    body2SemiBold: TextStyleConst.body2SemiBold,
    body2Medium: TextStyleConst.body2Medium,
    body2Regular: TextStyleConst.body2Regular,
    captionBold: TextStyleConst.captionBold,
    captionSemiBold: TextStyleConst.captionSemiBold,
    captionMedium: TextStyleConst.captionMedium,
    captionRegular: TextStyleConst.captionRegular,
  );
}
